<div class="meta-box-sortabless">
	<div id="wizard_page">
        <div class="postbox" id="sm_pnres">
            <h3 class="hndle"><span>About:</span></h3>
            <div class="inside">
                <a class="sm_button sm_pluginCommercial" href="https://manticoresearch.com/blog/manticoresearch-wordpress-plugin/">Plugin Website</a>
                <a class="sm_button sm_pluginHome" href="https://wp.manticoresearch.com/blog/article/1">Plugin
                    Tutorial</a>
                <a class="sm_button sm_pluginSupport" href="https://forum.manticoresearch.com/">Support Forum</a>
                <a class="sm_button sm_pluginSupport" href="https://slack.manticoresearch.com/">Slack</a>
                <a class="sm_button sm_pluginSupport" href="https://t.me/manticore_chat">Telegram</a>
            </div>
        </div>
        <div class="postbox" id="sm_pnres">
            <h3 class="hndle"><span>Support:</span></h3>
            <div class="inside">
                <p>
                    Need help? <a target="_blank" href="mailto:wp@manticoresearch.com">Contact us!</a>
                </p>
            </div>
        </div>
	</div>
</div>
</div>
</div>

