<div class="meta-box-sortabless">
	<?php
	if ( empty( $this->view->execute_disabled ) && empty( $this->view->blog_search_disabled ) ) { ?>
        <div class="postbox">
            <h3 class="hndle">Manticore service management</h3>
            <div class="inside">
                <form method="post" action="<?php echo $_SERVER["REQUEST_URI"]; ?>">
                    <fieldset class="options">
						<?php if ( ManticoreSearch::$plugin->sphinxQL->is_active() ): ?>
                            <span style="color:green">OK - Manticore Search is running.</span><br/>
						<?php else: ?>
                            <span style="color:red">Warning: Manticore Search is NOT running, you use default Wordpress search capabilities.</span>
                            <br/>
						<?php endif; ?>
                    </fieldset>
                    <p class="submit">
						<?php if ( ManticoreSearch::$plugin->sphinxQL->is_active() ): ?>
                            <input type="submit" style="width:300px;" name="stop_sphinx" class="button-primary"
								<?php if ( $this->view->devOptions['is_subdomain'] == 'true' ) {
									echo 'disabled';
								} ?>
                                   value="Stop Manticore daemon"
                                   onClick="if(!confirm('Do you really want to stop Manticore Search daemon now?'))return false;"
                            />
						<?php else: ?>
                            <input type="submit" style="width:300px;" name="start_sphinx" class="button-primary"
                                   value="Start Manticore daemon"/>
						<?php endif; ?>
                    </p>
                </form>
            </div>

            <div style="border-top:1px solid #CCC;"></div>

            <div class="inside">
                <span class="hidden" id='admin-url' data-url="<?php echo admin_url(); ?>"></span>
                <div>Indexed <span
                            class="indexing-info <?php if ( $this->view->indexing_data['indexed'] < $this->view->indexing_data['all_count'] ) {
								echo "red";
							} ?>" id="indexed_count"><?php echo $this->view->indexing_data['indexed'] ?></span>/<span
                            class="indexing-info"
                            id="index_all_count"><?php echo $this->view->indexing_data['all_count'] ?></span> documents
                    <span id="indexing_blog"></span>
                </div>
                <div id="indexing-log" class="indexing-log"></div>
                <form method="post" id="reindex_sphinx_form" action="<?php echo $_SERVER["REQUEST_URI"]; ?>">
                    <div id="indexing_progressbar">
                        <div class="progress-label"></div>
                    </div>
                    <p class="submit">
						<?php if ( ManticoreSearch::$plugin->sphinxQL->is_active() ): ?>
                            <input id='reindex_sphinx' type="submit" style="width:300px;" name="reindex_sphinx"
                                   class="button-primary"
                                   value="Index all posts now"/>
						<?php else: ?>
                            <input disabled type="submit" style="width:300px;" name="reindex_sphinx"
                                   class="button-primary disabled"
                                   value="Index all posts now"/>
						<?php endif; ?>
                    </p>
                </form>
				<?php
				if ( ManticoreSearch::$plugin->sphinxQL->is_active() && ! empty( $this->view->start_reindex ) && $this->view->start_reindex == 'true' ) {
					echo '<script>jQuery("#reindex_sphinx_form").submit()</script>';
				}
				?>
            </div>
        </div>
        <div class="postbox">
            <h3 class="hndle">Manticore Configuration Wizard</h3>
            <div class="inside">

				<?php if ( ! $this->view->is_sphinx_path_secure ): ?>
                    <p>
                        <span style="color:red">Warning: Manticore Search Plugin files are not secure!</span><br/>
                        <br/>
                        Please make sure the following files are inaccessible from web:<br/>
						<?php foreach ( $this->view->insecure_files as $file ) { ?>
                            <a href="<?php echo $file; ?>"><?php echo $file; ?></a><br/>
						<?php } ?>
                        <br/>
                        In case you can't fix this issue by yourself please contact your system administrator to help
                        you
                        protect those.
                    </p>
				<?php endif; ?>

                <form method="post" action="<?php echo $_SERVER["REQUEST_URI"]; ?>&menu=wizard">
                    <p class="submit">
                        <input type="hidden" name="start_wizard" value="start"/>
                        <input
							<?php if ( $this->view->devOptions['is_subdomain'] == 'true' ) {
								echo 'disabled';
							} ?>
                                type="submit" style="width:300px;"
                                class="button<?php if ( $this->view->devOptions['configured'] == 'false' ) {
									echo '-primary';
								} ?>"
							<?php if ( $this->view->devOptions['configured'] == 'true' ) { ?>
                                onClick="if(!confirm('Manticore is already configured. Are you sure you want to reconfigure the plugin?'))return false;"
							<?php } ?>
                                value="Run Manticore configuration Wizard"/>
                    </p>
                </form>
            </div>
        </div>
	<?php } elseif ( ! empty( $this->view->blog_search_disabled ) ) { ?>
        <div class="postbox">
            <div class="inside" style="background: #fff0f0;margin: 0;"><br>
                <p style="text-align:center; align-content:center; font-size: 1.2em;font-weight: bold; color: #ce4343;">
                    Plugin is deactivated on this blog. Contact your administrator</p>
            </div>

            <div style="border-top:1px solid #CCC;"></div>
        </div>
	<?php } else { ?>
        <div class="postbox">
            <div class="inside" style="background: #fff0f0;margin: 0;"><br>
                <p style="text-align:center; align-content:center; font-size: 1.2em;font-weight: bold; color: #ce4343;">
                    PHP function exec is disabled. Plugin can't work!</p>
            </div>

            <div style="border-top:1px solid #CCC;"></div>
        </div>
	<?php } ?>
</div>
</div>
</div>
